### ISSUE TITLE
Баг при установке capacity, имеющего размер -10000.

### ISSUE THREAD

**Issue by Amlola** [SANEKDASH/briken_stack#2]
1) Функция *GetRightDataCanaryPtr(const Stack *stk) и *GetLeftDataCanaryPtr(const Stack *stk) не являются статическими. Их можно вызвать в main().
2) Функция *GetRightDataCanaryPtr(const Stack *stk) не имеет проверки на валидное значение capacity. При установке capacity = -10000, мы залезаем в защищенную область памяти.

```C++
CanaryType_t *GetRightDataCanaryPtr(const Stack *stk)
          {
              return (CanaryType_t *)((char *)stk->details.data + stk->details.capacity * sizeof(StackType_t));
          }
```

Пример кода, при котором программа падает:
```C++
int main()
{
    LGIN;

    Stack stk = {};
    StackInit(&stk);

    stk.details.capacity = -10000;
    *GetRightDataCanaryPtr(&stk) = 0xDed;


    StackDtor(&stk);

    LGOUT;

    return 0;
}
```

**Comment by SANEKDASH** [comment]
I see. Thank you. I guess i should add stack limiter and make these functions static.
